// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zobxlwekyzjvnfcpsqfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYnhsd2VreXpqdm5mY3BzcWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzcyNjMsImV4cCI6MjA3MDU1MzI2M30._grcnCBitkJO9drMgdskgXAc33Dv2oLpTU6QT_jyeqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});